---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: projects.upm.syntropycloud.io
spec:
  group: upm.syntropycloud.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    shortNames:
    - pj
    singular: project
  scope: Cluster
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: Project is the Schema for the projects API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: ProjectSpec defines the desired state of Project
            properties:
              ca:
                description: CA contains information about the Certificate Authority
                  configuration.
                properties:
                  commonName:
                    description: CommonName is the common name for the CA certificate.
                    minLength: 1
                    type: string
                  duration:
                    description: Duration is the validity period of the CA certificate.
                    pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                  enabled:
                    description: Enabled indicates whether the CA is enabled.
                    type: boolean
                  privateKey:
                    description: PrivateKey contains information about the CA's private
                      key.
                    properties:
                      algorithm:
                        description: Algorithm is the cryptographic algorithm used
                          for the private key.
                        enum:
                        - RSA
                        - ECDSA
                        - Ed25519
                        type: string
                      size:
                        description: Size is the size of the private key in bits.
                        minimum: 1
                        type: integer
                    type: object
                  renewBefore:
                    description: RenewBefore is the time before expiration when the
                      certificate should be renewed.
                    pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                  secretName:
                    description: SecretName is the name of the Kubernetes secret storing
                      the CA.
                    pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                    type: string
                type: object
            type: object
          status:
            description: ProjectStatus defines the observed state of Project
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
